name: Build documentation
on:
  pull_request:
  workflow_dispatch:
    inputs:
      cache:
        description: 'Use build cache'
        required: false
        default: "true"

env:
  USE_CACHE: ${{ (github.event_name == 'workflow_dispatch' && github.event.inputs.cache == 'true') || (github.event_name == 'pull_request') }}

jobs:

  build:
    name: Build documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.2

      - uses: actions/setup-python@v4.0.0
        with:
          python-version: '3.10'

      - uses: syphar/restore-virtualenv@v1.2
        id: cache-virtualenv
        with:
          requirement_files: requirements.txt

      - name: Install OS packages
        run: |
          sudo apt-get update
          sudo apt-get install -y zip unzip libgl1-mesa-glx libenchant-2-2

      - name: Install dependencies
        if: steps.cache-virtualenv.outputs.cache-hit != 'true'
        run: pip install -r requirements.txt

      - name: Cache docs _build directory
        uses: actions/cache@v3.0.4
        if: env.USE_CACHE == 'true'
        with:
          path: docs/_build/
          key: docs-_build-${{ hashFiles('docs/source/conf.py') }}

      - name: Check spelling
        run: |
          cd docs
          make spelling

      - name: Build documentation
        run: |
          cd docs
          make html

      - name: Zip build
        run: |
          cp -r docs/_build/html build_docs
          zip -r build_docs build_docs

      - uses: actions/upload-artifact@v3.1.0
        with:
          name: build_docs
          path: build_docs.zip

  deploy:
    name: Publish documentation
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags')
    steps:
      - uses: actions/checkout@v2.4.2

      - uses: actions/download-artifact@v3.0.0
        with:
          name: build_docs
          path: .

      - name: Unzip build
        run: unzip build_docs.zip

      - name: Deploy on release
        if: startsWith(github.ref, 'refs/tags')
        uses: peaceiris/actions-gh-pages@v3.7.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build_docs